name-template: 'v$RESOLVED_VERSION 🌟'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'refactor'
  default: patch

categories:
  - title: '🚀 New Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '✨ Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '🛠️ Refactoring & Maintenance'
    labels:
      - 'refactor'
      - 'cleanup'
      - 'chore'
      - 'dependencies'
  - title: '📖 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚙️ CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'

template: |
  ## 🌟 Changes in this release:
  $CHANGES
