"""Initial migration - create all tables

Revision ID: b0192437ef34
Revises: 
Create Date: 2025-06-11 10:30:09.668061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0192437ef34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('immunizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('immunizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
