"""add_insurance

Revision ID: ce642f83d9a3
Revises: 26ce48bf1215
Create Date: 2025-07-25 20:47:24.442613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce642f83d9a3'
down_revision = '26ce48bf1215'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurances', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insurances', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insurances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('insurances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('idx_insurances_active', table_name='insurances')
    op.drop_index('idx_insurances_patient_id', table_name='insurances')
    op.drop_index('idx_insurances_status', table_name='insurances')
    op.drop_index('idx_insurances_type', table_name='insurances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_insurances_type', 'insurances', ['insurance_type'], unique=False)
    op.create_index('idx_insurances_status', 'insurances', ['status'], unique=False)
    op.create_index('idx_insurances_patient_id', 'insurances', ['patient_id'], unique=False)
    op.create_index('idx_insurances_active', 'insurances', ['status'], unique=False)
    op.alter_column('insurances', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('insurances', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('insurances', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('insurances', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
