"""Add missing effectivePeriod_start to medications

Revision ID: c4d543c69761
Revises: 7144f20f4b32
Create Date: 2025-06-11 23:21:39.484232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d543c69761'
down_revision = '7144f20f4b32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('name', sa.String(), nullable=True))
    op.add_column('medications', sa.Column('effectivePeriod_start', sa.Date(), nullable=True))
    op.add_column('treatments', sa.Column('treatment_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatments', 'treatment_name')
    op.drop_column('medications', 'effectivePeriod_start')
    op.drop_column('conditions', 'name')
    # ### end Alembic commands ###
