"""Initial migration - create all tables

Revision ID: 62f476a0b5fd
Revises:
Create Date: 2025-06-15 16:06:54.944365

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62f476a0b5fd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
