/**
 * Condition form field configuration
 */

import { tagsFieldConfig, getTodayEndOfDay } from './shared';

export const conditionFormFields = [
  {
    name: 'diagnosis',
    type: 'text',
    label: 'Diagnosis',
    placeholder: 'e.g., Hypertension, Diabetes Type 2, Asthma',
    required: true,
    description: 'Medical condition or diagnosis name',
    gridColumn: 12,
  },
  {
    name: 'status',
    type: 'select',
    label: 'Status',
    description: 'Current status of this condition',
    gridColumn: 6,
    dynamicOptions: 'conditionStatus',
  },
  {
    name: 'severity',
    type: 'select',
    label: 'Severity',
    placeholder: 'Select severity level',
    description: 'Severity level of this condition',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'severity',
  },
  {
    name: 'medication_id',
    type: 'select',
    label: 'Related Medication',
    placeholder: 'Select medication (optional)',
    description: 'Link this condition to a specific medication',
    gridColumn: 12,
    searchable: true,
    clearable: true,
    dynamicOptions: 'medications',
  },
  {
    name: 'onset_date',
    type: 'date',
    label: 'Onset Date',
    placeholder: 'When did this condition start',
    description: 'When this condition was first diagnosed',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'end_date',
    type: 'date',
    label: 'End Date',
    placeholder: 'When was this condition resolved',
    description: 'When this condition was resolved (optional)',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'icd10_code',
    type: 'text',
    label: 'ICD-10 Code',
    placeholder: 'e.g., I10, E11.9',
    description: 'International Classification of Diseases code',
    gridColumn: 4,
    maxLength: 10,
  },
  {
    name: 'snomed_code',
    type: 'text',
    label: 'SNOMED Code',
    placeholder: 'e.g., 38341003',
    description: 'SNOMED CT clinical terminology code',
    gridColumn: 4,
    maxLength: 20,
  },
  {
    name: 'code_description',
    type: 'text',
    label: 'Code Description',
    placeholder: 'Description of the medical code',
    description: 'Human-readable description of the code',
    gridColumn: 4,
    maxLength: 500,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Notes',
    placeholder: 'Additional information about this condition...',
    description: 'Treatment notes, symptoms, or other relevant details',
    gridColumn: 12,
    minRows: 4,
    maxRows: 8,
  },
  tagsFieldConfig,
];
