/**
 * Family Condition form field configuration
 */

export const familyConditionFormFields = [
  {
    name: 'condition_name',
    type: 'text',
    label: 'Condition Name',
    placeholder: 'e.g., Diabetes, Heart Disease, Cancer',
    required: true,
    description: 'Name of the medical condition',
    gridColumn: 6,
  },
  {
    name: 'condition_type',
    type: 'select',
    label: 'Condition Type',
    placeholder: 'Select condition type',
    description: 'Category of medical condition',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      {
        value: 'cardiovascular',
        label: 'Cardiovascular - Heart & blood vessels',
      },
      { value: 'diabetes', label: 'Diabetes - Blood sugar disorders' },
      { value: 'cancer', label: 'Cancer - Malignant conditions' },
      {
        value: 'mental_health',
        label: 'Mental Health - Psychological conditions',
      },
      { value: 'neurological', label: 'Neurological - Brain & nervous system' },
      { value: 'autoimmune', label: 'Autoimmune - Immune system disorders' },
      { value: 'genetic', label: 'Genetic - Hereditary conditions' },
      {
        value: 'respiratory',
        label: 'Respiratory - Lung & breathing conditions',
      },
      { value: 'endocrine', label: 'Endocrine - Hormone disorders' },
      { value: 'other', label: 'Other - Specify in notes' },
    ],
  },
  {
    name: 'severity',
    type: 'select',
    label: 'Severity',
    placeholder: 'Select severity level',
    description: 'How severe the condition was/is',
    gridColumn: 4,
    clearable: true,
    options: [
      { value: 'mild', label: '💛 Mild - Minor impact' },
      { value: 'moderate', label: '⚡ Moderate - Noticeable impact' },
      { value: 'severe', label: '⚠️ Severe - Significant impact' },
      { value: 'critical', label: '🚨 Critical - Life-threatening' },
    ],
  },
  {
    name: 'diagnosis_age',
    type: 'number',
    label: 'Diagnosis Age',
    placeholder: 'e.g., 45',
    description: 'Age at diagnosis',
    gridColumn: 4,
    min: 0,
    max: 120,
  },
  {
    name: 'status',
    type: 'select',
    label: 'Status',
    placeholder: 'Select status',
    description: 'Current status of the condition',
    gridColumn: 4,
    clearable: true,
    options: [
      { value: 'active', label: 'Active - Ongoing condition' },
      { value: 'resolved', label: 'Resolved - No longer present' },
      { value: 'chronic', label: 'Chronic - Long-term condition' },
    ],
  },
  {
    name: 'icd10_code',
    type: 'text',
    label: 'ICD-10 Code',
    placeholder: 'e.g., E11.9',
    description: 'Medical diagnosis code (if known)',
    gridColumn: 6,
    maxLength: 10,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Notes',
    placeholder: 'Additional details about the condition...',
    description: 'Treatment details, outcomes, or other relevant information',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
];
