/**
 * Family Member form field configuration
 */

export const familyMemberFormFields = [
  {
    name: 'name',
    type: 'text',
    label: 'Full Name',
    placeholder: 'Enter family member name',
    required: true,
    description: 'Full name of the family member',
    gridColumn: 6,
  },
  {
    name: 'relationship',
    type: 'select',
    label: 'Relationship',
    placeholder: 'Select relationship',
    required: true,
    description: 'Relationship to you',
    gridColumn: 6,
    searchable: true,
    options: [
      { value: 'father', label: 'Father' },
      { value: 'mother', label: 'Mother' },
      { value: 'brother', label: 'Brother' },
      { value: 'sister', label: 'Sister' },
      { value: 'paternal_grandfather', label: 'Paternal Grandfather' },
      { value: 'paternal_grandmother', label: 'Paternal Grandmother' },
      { value: 'maternal_grandfather', label: 'Maternal Grandfather' },
      { value: 'maternal_grandmother', label: 'Maternal Grandmother' },
      { value: 'uncle', label: 'Uncle' },
      { value: 'aunt', label: 'Aunt' },
      { value: 'cousin', label: 'Cousin' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'gender',
    type: 'select',
    label: 'Gender',
    placeholder: 'Select gender',
    description: 'Gender of family member',
    gridColumn: 4,
    clearable: true,
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'birth_year',
    type: 'number',
    label: 'Birth Year',
    placeholder: 'e.g., 1965',
    description: 'Year family member was born',
    gridColumn: 4,
    min: 1900,
    max: new Date().getFullYear(),
  },
  {
    name: 'is_deceased',
    type: 'checkbox',
    label: 'Deceased',
    description: 'Check if family member is deceased',
    gridColumn: 4,
  },
  {
    name: 'death_year',
    type: 'number',
    label: 'Death Year',
    placeholder: 'e.g., 2020',
    description: 'Year family member passed away',
    gridColumn: 6,
    min: 1900,
    max: new Date().getFullYear(),
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Notes',
    placeholder: 'Additional information about family member...',
    description: 'Any additional notes or important information',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
];
