/**
 * Immunization form field configuration
 */

import { tagsFieldConfig } from './shared';

export const immunizationFormFields = [
  {
    name: 'vaccine_name',
    type: 'text',
    label: 'Vaccine Name',
    placeholder: 'e.g., COVID-19 mRNA, Influenza, MMR',
    required: true,
    description: 'Name of the administered vaccine',
    gridColumn: 12,
  },
  {
    name: 'date_administered',
    type: 'date',
    label: 'Date Administered',
    placeholder: 'Select administration date',
    required: true,
    description: 'When the vaccine was given',
    gridColumn: 8,
  },
  {
    name: 'dose_number',
    type: 'number',
    label: 'Dose Number',
    placeholder: '1, 2, 3...',
    description: 'Which dose in series',
    gridColumn: 4,
    min: 1,
    max: 10,
  },
  {
    name: 'lot_number',
    type: 'text',
    label: 'Lot Number',
    placeholder: 'Vaccine batch/lot number',
    description: 'Batch identifier for tracking',
    gridColumn: 6,
  },
  {
    name: 'ndc_number',
    type: 'text',
    label: 'NDC Number',
    placeholder: 'e.g., 12345-6789-01',
    description: 'National Drug Code for the vaccine',
    gridColumn: 6,
  },
  {
    name: 'manufacturer',
    type: 'select',
    label: 'Manufacturer',
    placeholder: 'Select manufacturer',
    description: 'Vaccine manufacturer',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'manufacturers',
  },
  {
    name: 'site',
    type: 'select',
    label: 'Injection Site',
    placeholder: 'Select injection site',
    description: 'Location where vaccine was given',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'sites',
  },
  {
    name: 'route',
    type: 'select',
    label: 'Administration Route',
    placeholder: 'Select route',
    description: 'Method of administration',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'routes',
  },
  {
    name: 'expiration_date',
    type: 'date',
    label: 'Vaccine Expiration Date',
    placeholder: 'Select expiration date',
    description: 'Expiration date of the vaccine vial/dose used',
    gridColumn: 12,
  },
  {
    name: 'location',
    type: 'text',
    label: 'Location',
    placeholder: 'e.g., CVS Pharmacy, Hospital, Clinic, Health Department',
    description: 'Where the vaccine was administered',
    gridColumn: 12,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Any reactions, side effects, or additional observations...',
    description: 'Record any adverse reactions or important notes',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
