/**
 * Insurance form field configuration
 */

import { tagsFieldConfig } from './shared';

export const insuranceFormFields = [
  // === SECTION 1: Basic Insurance Information ===
  {
    name: '_divider_basic',
    type: 'divider',
    label: 'Basic Insurance Information',
    gridColumn: 12,
  },
  {
    name: 'insurance_type',
    type: 'select',
    label: 'Insurance Type',
    placeholder: 'Select insurance type',
    required: true,
    description: 'Type of insurance coverage',
    gridColumn: 6,
    options: [
      { value: 'medical', label: '🏥 Medical Insurance' },
      { value: 'dental', label: '🦷 Dental Insurance' },
      { value: 'vision', label: '👁️ Vision Insurance' },
      { value: 'prescription', label: '💊 Prescription Insurance' },
    ],
  },
  {
    name: 'company_name',
    type: 'text',
    label: 'Insurance Company',
    placeholder: 'e.g., Blue Cross Blue Shield',
    required: true,
    description: 'Name of the insurance company',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'plan_name',
    type: 'text',
    label: 'Plan Name',
    placeholder: 'e.g., PPO Gold Plus',
    description: 'Name of the specific insurance plan',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'employer_group',
    type: 'text',
    label: 'Employer/Group Sponsor',
    placeholder: 'e.g., ABC Corporation, Self-Employed',
    description: 'Company or organization providing the insurance (if applicable)',
    gridColumn: 6,
    maxLength: 255,
  },

  // === SECTION 2: Member Information ===
  {
    name: '_divider_member',
    type: 'divider',
    label: 'Member Information',
    gridColumn: 12,
  },
  {
    name: 'member_name',
    type: 'text',
    label: 'Member Name',
    placeholder: 'e.g., John Doe',
    required: true,
    description: 'Name as it appears on the insurance card',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'member_id',
    type: 'text',
    label: 'Member ID',
    placeholder: 'e.g., ABC123456789',
    required: true,
    description: 'Member ID number from insurance card',
    gridColumn: 6,
    maxLength: 100,
  },
  {
    name: 'policy_holder_name',
    type: 'text',
    label: 'Policy Holder Name',
    placeholder: 'e.g., Jane Doe (leave blank if same as member)',
    description: 'Name of policy holder (if different from member)',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'relationship_to_holder',
    type: 'select',
    label: 'Relationship to Holder',
    placeholder: 'Select relationship',
    description: 'Your relationship to the policy holder',
    gridColumn: 6,
    clearable: true,
    options: [
      { value: 'self', label: 'Self' },
      { value: 'spouse', label: 'Spouse' },
      { value: 'child', label: 'Child' },
      { value: 'dependent', label: 'Dependent' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'group_number',
    type: 'text',
    label: 'Group Number',
    placeholder: 'e.g., GRP123',
    description: 'Group number (if applicable)',
    gridColumn: 6,
    maxLength: 100,
  },

  // === SECTION 3: Coverage Period & Status ===
  {
    name: '_divider_coverage',
    type: 'divider',
    label: 'Coverage Period & Status',
    gridColumn: 12,
  },
  {
    name: 'effective_date',
    type: 'date',
    label: 'Effective Date',
    placeholder: 'Select effective date',
    required: true,
    description: 'Date when coverage begins',
    gridColumn: 6,
  },
  {
    name: 'expiration_date',
    type: 'date',
    label: 'Expiration Date',
    placeholder: 'Select expiration date',
    description: 'Date when coverage ends (if known)',
    gridColumn: 6,
  },
  {
    name: 'status',
    type: 'select',
    label: 'Status',
    placeholder: 'Select status',
    required: true,
    description: 'Current status of the insurance',
    gridColumn: 6,
    clearable: false,
    options: [
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' },
      { value: 'expired', label: 'Expired' },
      { value: 'pending', label: 'Pending' },
    ],
  },
  {
    name: 'is_primary',
    type: 'checkbox',
    label: 'Primary Insurance',
    description: 'Check if this is your primary insurance (for medical only)',
    gridColumn: 6,
  },

  // === SECTION 4: Contact Information ===
  {
    name: '_divider_contact',
    type: 'divider',
    label: 'Contact Information',
    gridColumn: 12,
  },
  {
    name: 'customer_service_phone',
    type: 'tel',
    label: 'Customer Service Phone',
    placeholder: 'e.g., 1-800-123-4567',
    description: 'Customer service phone number',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical', 'dental', 'vision', 'prescription'],
  },
  {
    name: 'preauth_phone',
    type: 'tel',
    label: 'Pre-authorization Phone',
    placeholder: 'e.g., 1-800-123-4567',
    description: 'Phone number for pre-authorizations',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical'],
  },
  {
    name: 'provider_services_phone',
    type: 'tel',
    label: 'Provider Services Phone',
    placeholder: 'e.g., 1-800-123-4567',
    description: 'Phone number for provider services',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical', 'dental'],
  },
  {
    name: 'website_url',
    type: 'url',
    label: 'Website URL',
    placeholder: 'e.g., https://member.insurance.com',
    description: 'Member portal or website URL',
    gridColumn: 6,
    showFor: ['medical', 'dental', 'vision', 'prescription'],
  },
  {
    name: 'claims_address',
    type: 'textarea',
    label: 'Claims Address',
    placeholder: 'Enter claims mailing address...',
    description: 'Address for submitting claims',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
    showFor: ['medical', 'dental', 'vision'],
  },

  // === SECTION 5: Coverage Details (Type-Specific) ===
  {
    name: '_divider_coverage_details',
    type: 'divider',
    label: 'Coverage Details',
    gridColumn: 12,
  },

  // Medical Insurance Fields
  {
    name: 'primary_care_physician',
    type: 'text',
    label: 'Primary Care Physician',
    placeholder: 'e.g., Dr. Smith',
    description: 'Name of your primary care physician',
    gridColumn: 6,
    maxLength: 255,
    showFor: ['medical'],
  },
  {
    name: 'deductible_individual',
    type: 'number',
    label: 'Individual Deductible',
    placeholder: 'e.g., 1000',
    description: 'Annual deductible amount for individual',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'deductible_family',
    type: 'number',
    label: 'Family Deductible',
    placeholder: 'e.g., 2000',
    description: 'Annual deductible amount for family',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_primary_care',
    type: 'number',
    label: 'Primary Care Copay',
    placeholder: 'e.g., 25',
    description: 'Copay amount for primary care visits',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_specialist',
    type: 'number',
    label: 'Specialist Copay',
    placeholder: 'e.g., 50',
    description: 'Copay amount for specialist visits',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_emergency_room',
    type: 'number',
    label: 'Emergency Room Copay',
    placeholder: 'e.g., 200',
    description: 'Copay amount for emergency room visits',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_urgent_care',
    type: 'number',
    label: 'Urgent Care Copay',
    placeholder: 'e.g., 75',
    description: 'Copay amount for urgent care visits',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },

  // Medical Insurance Plan Type
  {
    name: 'plan_type',
    type: 'select',
    label: 'Plan Type',
    placeholder: 'Select plan type',
    description: 'Type of medical insurance plan',
    gridColumn: 6,
    showFor: ['medical'],
    options: [
      { value: 'ppo', label: 'PPO (Preferred Provider Organization)' },
      { value: 'hmo', label: 'HMO (Health Maintenance Organization)' },
      { value: 'epo', label: 'EPO (Exclusive Provider Organization)' },
      { value: 'pos', label: 'POS (Point of Service)' },
      { value: 'hdhp', label: 'HDHP (High Deductible Health Plan)' },
      { value: 'indemnity', label: 'Indemnity (Fee-for-Service)' },
      { value: 'other', label: 'Other' },
    ],
  },

  // Dental Insurance Plan Type
  {
    name: 'dental_plan_type',
    type: 'select',
    label: 'Dental Plan Type',
    placeholder: 'Select dental plan type',
    description: 'Type of dental insurance plan',
    gridColumn: 6,
    showFor: ['dental'],
    options: [
      { value: 'dppo', label: 'DPPO (Dental Preferred Provider Organization)' },
      { value: 'dhmo', label: 'DHMO (Dental Health Maintenance Organization)' },
      { value: 'indemnity', label: 'Indemnity (Fee-for-Service)' },
      { value: 'discount', label: 'Discount Plan' },
      { value: 'other', label: 'Other' },
    ],
  },

  // Vision Insurance Plan Type
  {
    name: 'vision_plan_type',
    type: 'select',
    label: 'Vision Plan Type',
    placeholder: 'Select vision plan type',
    description: 'Type of vision insurance plan',
    gridColumn: 6,
    showFor: ['vision'],
    options: [
      { value: 'vision_ppo', label: 'Vision PPO' },
      { value: 'vision_hmo', label: 'Vision HMO' },
      { value: 'vision_discount', label: 'Vision Discount Plan' },
      { value: 'other', label: 'Other' },
    ],
  },

  // Prescription Plan Type
  {
    name: 'prescription_plan_type',
    type: 'select',
    label: 'Prescription Plan Type',
    placeholder: 'Select prescription plan type',
    description: 'Type of prescription drug plan',
    gridColumn: 6,
    showFor: ['prescription'],
    options: [
      { value: 'formulary', label: 'Formulary-Based Plan' },
      { value: 'tiered_copay', label: 'Tiered Copay Plan' },
      { value: 'medicare_part_d', label: 'Medicare Part D' },
      { value: 'integrated', label: 'Integrated with Medical' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'annual_maximum',
    type: 'number',
    label: 'Annual Maximum Benefit',
    placeholder: 'e.g., 1500',
    description: 'Maximum annual benefit amount',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'preventive_coverage',
    type: 'number',
    label: 'Preventive Coverage %',
    placeholder: 'e.g., 100',
    description: 'Coverage percentage for preventive care',
    gridColumn: 4,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'basic_coverage',
    type: 'number',
    label: 'Basic Coverage %',
    placeholder: 'e.g., 80',
    description: 'Coverage percentage for basic procedures',
    gridColumn: 6,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'major_coverage',
    type: 'number',
    label: 'Major Coverage %',
    placeholder: 'e.g., 50',
    description: 'Coverage percentage for major procedures',
    gridColumn: 6,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },

  // Vision Insurance Fields
  {
    name: 'exam_copay',
    type: 'number',
    label: 'Exam Copay',
    placeholder: 'e.g., 10',
    description: 'Copay amount for eye exams',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },
  {
    name: 'frame_allowance',
    type: 'number',
    label: 'Frame Allowance',
    placeholder: 'e.g., 150',
    description: 'Annual allowance for frames',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },
  {
    name: 'lens_coverage',
    type: 'text',
    label: 'Lens Coverage',
    placeholder: 'e.g., 100% covered',
    description: 'Coverage details for lenses',
    gridColumn: 6,
    showFor: ['vision'],
  },
  {
    name: 'contact_allowance',
    type: 'number',
    label: 'Contact Lens Allowance',
    placeholder: 'e.g., 150',
    description: 'Annual allowance for contact lenses',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },

  // Prescription Insurance Fields
  {
    name: 'bin_number',
    type: 'text',
    label: 'BIN Number',
    placeholder: 'e.g., 123456',
    description: 'Bank Identification Number for pharmacy',
    gridColumn: 4,
    maxLength: 10,
    showFor: ['prescription'],
    required: true,
    requiredFor: ['prescription'],
  },
  {
    name: 'pcn_number',
    type: 'text',
    label: 'PCN Number',
    placeholder: 'e.g., ABC123',
    description: 'Processor Control Number',
    gridColumn: 4,
    maxLength: 10,
    showFor: ['prescription'],
    required: true,
    requiredFor: ['prescription'],
  },
  {
    name: 'rxgroup',
    type: 'text',
    label: 'RX Group',
    placeholder: 'e.g., RXGRP123',
    description: 'Prescription group number',
    gridColumn: 4,
    maxLength: 15,
    showFor: ['prescription'],
  },
  {
    name: 'copay_generic',
    type: 'number',
    label: 'Generic Copay',
    placeholder: 'e.g., 10',
    description: 'Copay amount for generic medications',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'copay_brand',
    type: 'number',
    label: 'Brand Name Copay',
    placeholder: 'e.g., 30',
    description: 'Copay amount for brand name medications',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'copay_specialty',
    type: 'number',
    label: 'Specialty Copay',
    placeholder: 'e.g., 75',
    description: 'Copay amount for specialty medications',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'pharmacy_network_info',
    type: 'textarea',
    label: 'Pharmacy Network Info',
    placeholder: 'Enter pharmacy network details...',
    description: 'Information about preferred pharmacy networks',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
    showFor: ['prescription'],
  },

  // === SECTION 6: Additional Information ===
  {
    name: '_divider_notes',
    type: 'divider',
    label: 'Additional Information',
    gridColumn: 12,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Notes',
    placeholder: 'Additional information about this insurance...',
    description: 'Any additional details or notes',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
