/**
 * Lab Result form field configuration
 */

import { tagsFieldConfig } from './shared';

export const labResultFormFields = [
  {
    name: 'test_name',
    type: 'text',
    labelKey: 'labresults:testName.label',
    placeholderKey: 'labresults:testName.placeholder',
    descriptionKey: 'labresults:testName.description',
    required: true,
    gridColumn: 8,
  },
  {
    name: 'test_code',
    type: 'text',
    labelKey: 'shared:fields.testCode',
    placeholderKey: 'labresults:testCode.placeholder',
    descriptionKey: 'labresults:testCode.description',
    gridColumn: 4,
  },
  {
    name: 'test_category',
    type: 'select',
    labelKey: 'labresults:testCategory.label',
    placeholderKey: 'shared:labels.selectCategory',
    descriptionKey: 'labresults:testCategory.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'categories',
  },
  {
    name: 'test_type',
    type: 'select',
    labelKey: 'labresults:testTypeField.label',
    placeholderKey: 'labresults:testTypeField.placeholder',
    descriptionKey: 'labresults:testTypeField.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'testTypes',
  },
  {
    name: 'facility',
    type: 'text',
    labelKey: 'labresults:testingFacility.label',
    placeholderKey: 'labresults:testingFacility.placeholder',
    descriptionKey: 'labresults:testingFacility.description',
    gridColumn: 6,
  },
  {
    name: 'practitioner_id',
    type: 'select',
    labelKey: 'shared:labels.orderingPractitioner',
    placeholderKey: 'shared:labels.selectPractitioner',
    descriptionKey: 'labresults:orderingPractitioner.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'status',
    type: 'select',
    labelKey: 'labresults:testStatus.label',
    placeholderKey: 'labresults:testStatus.placeholder',
    descriptionKey: 'labresults:testStatus.description',
    gridColumn: 6,
    dynamicOptions: 'statuses',
  },
  {
    name: 'labs_result',
    type: 'select',
    labelKey: 'shared:labels.labResult',
    placeholderKey: 'labresults:labResult.placeholder',
    descriptionKey: 'labresults:labResult.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'results',
  },
  {
    name: 'ordered_date',
    type: 'date',
    labelKey: 'shared:labels.orderedDate',
    placeholderKey: 'labresults:orderedDate.placeholder',
    descriptionKey: 'labresults:orderedDate.description',
    gridColumn: 6,
  },
  {
    name: 'completed_date',
    type: 'date',
    labelKey: 'shared:labels.completedDate',
    placeholderKey: 'labresults:completedDate.placeholder',
    descriptionKey: 'labresults:completedDate.description',
    gridColumn: 6,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:fields.additionalNotes',
    placeholderKey: 'labresults:additionalNotes.placeholder',
    descriptionKey: 'labresults:additionalNotes.description',
    gridColumn: 12,
    minRows: 4,
    maxRows: 12,
    maxLength: 5000,
  },
  tagsFieldConfig,
];
