/**
 * Medication form field configuration
 */

import {
  MEDICATION_TYPES,
  MEDICATION_TYPE_LABELS,
} from '../../constants/medicationTypes';
import { tagsFieldConfig } from './shared';

export const medicationFormFields = [
  {
    name: 'medication_name',
    type: 'text',
    labelKey: 'medical:medications.medicationName.label',
    placeholderKey: 'medical:medications.medicationName.placeholder',
    descriptionKey: 'medical:medications.medicationName.description',
    required: true,
    gridColumn: 6,
    minLength: 2,
    maxLength: 255,
  },
  {
    name: 'medication_type',
    type: 'select',
    labelKey: 'medical:medications.medicationType.label',
    placeholderKey: 'medical:medications.medicationType.placeholder',
    descriptionKey: 'medical:medications.medicationType.description',
    required: true,
    gridColumn: 6,
    options: Object.keys(MEDICATION_TYPES).map(key => ({
      value: MEDICATION_TYPES[key],
      label: MEDICATION_TYPE_LABELS[MEDICATION_TYPES[key]],
    })),
  },
  {
    name: 'dosage',
    type: 'text',
    labelKey: 'medical:medications.dosage.label',
    placeholderKey: 'medical:medications.dosage.placeholder',
    descriptionKey: 'medical:medications.dosage.description',
    gridColumn: 6,
  },
  {
    name: 'frequency',
    type: 'text',
    labelKey: 'medical:medications.frequency.label',
    placeholderKey: 'medical:medications.frequency.placeholder',
    descriptionKey: 'medical:medications.frequency.description',
    gridColumn: 6,
  },
  {
    name: 'route',
    type: 'select',
    labelKey: 'medical:medications.route.label',
    placeholderKey: 'medical:medications.route.placeholder',
    descriptionKey: 'medical:medications.route.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      { value: 'oral', labelKey: 'medical:medications.route.options.oral' },
      { value: 'injection', labelKey: 'medical:medications.route.options.injection' },
      { value: 'topical', labelKey: 'medical:medications.route.options.topical' },
      { value: 'intravenous', labelKey: 'medical:medications.route.options.intravenous' },
      { value: 'intramuscular', labelKey: 'medical:medications.route.options.intramuscular' },
      { value: 'subcutaneous', labelKey: 'medical:medications.route.options.subcutaneous' },
      { value: 'inhalation', labelKey: 'medical:medications.route.options.inhalation' },
      { value: 'nasal', labelKey: 'medical:medications.route.options.nasal' },
      { value: 'rectal', labelKey: 'medical:medications.route.options.rectal' },
      { value: 'sublingual', labelKey: 'medical:medications.route.options.sublingual' },
    ],
  },
  {
    name: 'indication',
    type: 'text',
    labelKey: 'medical:medications.indication.label',
    placeholderKey: 'medical:medications.indication.placeholder',
    descriptionKey: 'medical:medications.indication.description',
    gridColumn: 12,
  },
  {
    name: 'status',
    type: 'select',
    labelKey: 'common:fields.status.label',
    descriptionKey: 'common:fields.status.description',
    gridColumn: 4,
    options: [
      { value: 'active', labelKey: 'common:status.active' },
      { value: 'stopped', labelKey: 'common:status.stopped' },
      { value: 'on-hold', labelKey: 'common:status.onHold' },
      { value: 'completed', labelKey: 'common:status.completed' },
    ],
  },
  {
    name: 'effective_period_start',
    type: 'date',
    labelKey: 'common:fields.startDate.label',
    placeholderKey: 'common:fields.startDate.placeholder',
    descriptionKey: 'common:fields.startDate.description',
    gridColumn: 4,
  },
  {
    name: 'effective_period_end',
    type: 'date',
    labelKey: 'common:fields.endDate.label',
    placeholderKey: 'common:fields.endDate.placeholder',
    descriptionKey: 'common:fields.endDate.description',
    gridColumn: 4,
  },
  {
    name: 'practitioner_id',
    type: 'select',
    labelKey: 'medical:medications.prescribingProvider.label',
    placeholderKey: 'medical:medications.prescribingProvider.placeholder',
    descriptionKey: 'medical:medications.prescribingProvider.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    maxDropdownHeight: 200,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'pharmacy_id',
    type: 'select',
    labelKey: 'medical:medications.pharmacy.label',
    placeholderKey: 'medical:medications.pharmacy.placeholder',
    descriptionKey: 'medical:medications.pharmacy.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    maxDropdownHeight: 200,
    dynamicOptions: 'pharmacies',
  },
  tagsFieldConfig,
];
