/**
 * Pharmacy form field configuration
 */

export const pharmacyFormFields = [
  {
    name: 'brand',
    type: 'select',
    label: 'Pharmacy Brand',
    placeholder: 'Select pharmacy chain or type',
    description: 'Major pharmacy chain or independent type',
    gridColumn: 12,
    searchable: true,
    clearable: true,
    options: [
      { value: 'Amazon Pharmacy', label: 'Amazon Pharmacy' },
      { value: 'CVS', label: 'CVS Pharmacy' },
      { value: 'Walgreens', label: 'Walgreens' },
      { value: 'Rite Aid', label: 'Rite Aid' },
      { value: 'Walmart Pharmacy', label: 'Walmart Pharmacy' },
      { value: 'Target Pharmacy', label: 'Target Pharmacy' },
      { value: 'Costco Pharmacy', label: 'Costco Pharmacy' },
      { value: 'Kroger Pharmacy', label: 'Kroger Pharmacy' },
      { value: 'Safeway Pharmacy', label: 'Safeway Pharmacy' },
      { value: 'Publix Pharmacy', label: 'Publix Pharmacy' },
      { value: 'Meijer Pharmacy', label: 'Meijer Pharmacy' },
      { value: 'H-E-B Pharmacy', label: 'H-E-B Pharmacy' },
      { value: 'Kaiser Permanente', label: 'Kaiser Permanente' },
      { value: 'Hospital Pharmacy', label: 'Hospital Pharmacy' },
      { value: 'Independent', label: 'Independent Pharmacy' },
      { value: 'Specialty Pharmacy', label: 'Specialty Pharmacy' },
      { value: 'Compounding Pharmacy', label: 'Compounding Pharmacy' },
      { value: 'Online Pharmacy', label: 'Online Pharmacy' },
      { value: 'Other', label: 'Other' },
    ],
  },
  {
    name: 'name',
    type: 'text',
    label: 'Pharmacy Name',
    placeholder: 'CVS Pharmacy - Main Street',
    required: true,
    description: 'Specific name or location identifier',
    gridColumn: 12,
  },
  {
    name: '_divider_location',
    type: 'divider',
    label: 'Location Information',
    gridColumn: 12,
  },
  {
    name: 'street_address',
    type: 'text',
    label: 'Street Address',
    placeholder: '123 Main Street',
    description: 'Physical street address',
    gridColumn: 8,
  },
  {
    name: 'city',
    type: 'text',
    label: 'City',
    placeholder: 'San Francisco',
    description: 'City location',
    gridColumn: 4,
  },
  {
    name: 'store_number',
    type: 'text',
    label: 'Store Number',
    placeholder: 'e.g., 1234, #5678, Store A',
    description: 'Internal store identifier',
    gridColumn: 6,
    maxLength: 20,
  },
  {
    name: 'phone_number',
    type: 'tel',
    label: 'Phone Number',
    placeholder: '(555) 123-4567',
    description: 'Primary pharmacy phone number',
    gridColumn: 6,
    maxLength: 20,
  },
  {
    name: 'website',
    type: 'text',
    label: 'Website',
    placeholder: 'https://www.pharmacy-website.com',
    description: 'Pharmacy website or online services',
    gridColumn: 12,
  },
];
