/**
 * Symptom Occurrence form field configuration
 * For logging individual episodes
 */

import { getTodayEndOfDay } from './shared';

export const symptomOccurrenceFormFields = [
  {
    name: 'occurrence_date',
    type: 'date',
    label: 'Occurrence Date',
    placeholder: 'When did this episode occur',
    required: true,
    description: 'Date of this specific episode',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'occurrence_time',
    type: 'time',
    label: 'Time',
    placeholder: 'When did this episode start',
    description: 'Approximate time when this episode began',
    gridColumn: 6,
  },
  {
    name: 'severity',
    type: 'select',
    label: 'Severity',
    placeholder: 'Select severity level',
    required: true,
    description: 'How severe was this episode',
    gridColumn: 6,
    options: [
      {
        value: 'mild',
        label: 'Mild - Minor discomfort',
      },
      {
        value: 'moderate',
        label: 'Moderate - Noticeable impact',
      },
      {
        value: 'severe',
        label: 'Severe - Significant distress',
      },
      {
        value: 'critical',
        label: 'Critical - Emergency level',
      },
    ],
  },
  {
    name: 'pain_scale',
    type: 'number',
    label: 'Pain Scale (0-10)',
    placeholder: '0 = No pain, 10 = Worst pain',
    description: 'Rate pain level from 0 (none) to 10 (worst possible)',
    gridColumn: 6,
    min: 0,
    max: 10,
    step: 1,
  },
  {
    name: 'duration',
    type: 'text',
    label: 'Duration',
    placeholder: 'e.g., 2 hours, 30 minutes, all day',
    description: 'How long did this episode last',
    gridColumn: 6,
    maxLength: 100,
  },
  {
    name: 'location',
    type: 'text',
    label: 'Body Location',
    placeholder: 'e.g., Left temple, Lower back, Entire body',
    description: 'Where on your body did you feel this',
    gridColumn: 6,
    maxLength: 200,
  },
  {
    name: 'impact_level',
    type: 'select',
    label: 'Impact on Daily Life',
    placeholder: 'Select impact level',
    description: 'How much did this affect your daily activities',
    gridColumn: 12,
    clearable: true,
    options: [
      { value: 'no_impact', label: 'No Impact - Able to function normally' },
      { value: 'mild', label: 'Mild - Slight difficulty with activities' },
      { value: 'moderate', label: 'Moderate - Some activities limited' },
      { value: 'severe', label: 'Severe - Most activities difficult' },
      { value: 'debilitating', label: 'Debilitating - Unable to function' },
    ],
  },
  {
    name: 'triggers',
    type: 'text',
    label: 'Triggers',
    placeholder: 'What triggered this episode (stress, food, weather, etc.)',
    description: 'Factors that may have caused or worsened this episode',
    gridColumn: 12,
  },
  {
    name: 'relief_methods',
    type: 'text',
    label: 'Relief Methods',
    placeholder: 'What helped (medication, rest, ice, etc.)',
    description: 'Things that provided relief for this episode',
    gridColumn: 12,
  },
  {
    name: 'associated_symptoms',
    type: 'text',
    label: 'Associated Symptoms',
    placeholder: 'Other symptoms (nausea, dizziness, etc.)',
    description: 'Other symptoms that occurred with this episode',
    gridColumn: 12,
  },
  {
    name: 'resolved_date',
    type: 'date',
    label: 'Resolved Date',
    placeholder: 'When did this episode resolve',
    description: 'Leave blank if still experiencing this episode',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'resolved_time',
    type: 'time',
    label: 'Resolved Time',
    placeholder: 'Time when episode resolved',
    description: 'Optional: specific time of resolution',
    gridColumn: 6,
  },
  {
    name: 'resolution_notes',
    type: 'textarea',
    label: 'Resolution Notes',
    placeholder: 'How was this episode resolved...',
    description: 'Details about how this episode ended or was treated',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
    maxLength: 2000,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Additional details about this episode...',
    description: 'Any other relevant information about this occurrence',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
    maxLength: 2000,
  },
];
