/**
 * Treatment form field configuration
 */

import { tagsFieldConfig } from './shared';

export const treatmentFormFields = [
  {
    name: 'treatment_name',
    type: 'text',
    label: 'Treatment Name',
    placeholder: 'e.g., Physical Therapy for Lower Back Pain',
    required: true,
    description: 'Specific name or description of the treatment',
    gridColumn: 7,
  },
  {
    name: 'treatment_type',
    type: 'select',
    label: 'Treatment Type',
    placeholder: 'Select type',
    description: 'Category of treatment',
    required: true,
    gridColumn: 5,
    searchable: true,
    options: [
      { value: 'Surgery', label: 'Surgery - Surgical procedure' },
      { value: 'Medication', label: 'Medication - Drug therapy' },
      { value: 'Physical Therapy', label: 'Physical Therapy - Rehabilitation' },
      { value: 'Chemotherapy', label: 'Chemotherapy - Cancer treatment' },
      { value: 'Radiation', label: 'Radiation - Radiation therapy' },
      {
        value: 'Immunotherapy',
        label: 'Immunotherapy - Immune system treatment',
      },
      {
        value: 'Occupational Therapy',
        label: 'Occupational Therapy - Functional improvement',
      },
      {
        value: 'Speech Therapy',
        label: 'Speech Therapy - Communication improvement',
      },
      {
        value: 'Behavioral Therapy',
        label: 'Behavioral Therapy - Mental health treatment',
      },
      { value: 'Dialysis', label: 'Dialysis - Kidney function support' },
      { value: 'Other', label: 'Other - Specify in description' },
    ],
  },
  {
    name: 'condition_id',
    type: 'select',
    label: 'Related Condition',
    placeholder: 'Select condition (optional)',
    description: 'Link this treatment to a specific medical condition',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'conditions',
  },
  {
    name: 'practitioner_id',
    type: 'select',
    label: 'Practitioner',
    placeholder: 'Select practitioner (optional)',
    description: 'Assign a practitioner to this treatment',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'status',
    type: 'select',
    label: 'Treatment Status',
    placeholder: 'Select status',
    description: 'Current stage in treatment workflow',
    gridColumn: 12,
    options: [
      { value: 'planned', label: 'Planned - Treatment scheduled for future' },
      { value: 'active', label: 'Active - Currently undergoing treatment' },
      { value: 'on-hold', label: 'On Hold - Temporarily paused' },
      {
        value: 'completed',
        label: 'Completed - Treatment finished successfully',
      },
      { value: 'cancelled', label: 'Cancelled - Treatment discontinued' },
    ],
  },
  {
    name: 'start_date',
    type: 'date',
    label: 'Start Date',
    placeholder: 'Select start date',
    required: true,
    description: 'When treatment begins/began',
    gridColumn: 6,
  },
  {
    name: 'end_date',
    type: 'date',
    label: 'End Date',
    placeholder: 'Select end date (if known)',
    description: 'Expected or actual completion date',
    gridColumn: 6,
  },
  {
    name: 'dosage',
    type: 'text',
    label: 'Amount',
    placeholder: 'e.g., 500mg, 2 tablets, 30 minutes',
    description: 'Amount or intensity per session',
    gridColumn: 6,
  },
  {
    name: 'frequency',
    type: 'select',
    label: 'Frequency',
    placeholder: 'Select frequency',
    description: 'How often treatment occurs',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      { value: 'Once daily', label: 'Once daily' },
      { value: 'Twice daily', label: 'Twice daily (BID)' },
      { value: 'Three times daily', label: 'Three times daily (TID)' },
      { value: 'Four times daily', label: 'Four times daily (QID)' },
      { value: 'Weekly', label: 'Weekly' },
      { value: 'Bi-weekly', label: 'Bi-weekly (every 2 weeks)' },
      { value: 'Monthly', label: 'Monthly' },
      { value: 'As needed', label: 'As needed (PRN)' },
      { value: 'One time', label: 'One time only' },
      { value: 'Continuous', label: 'Continuous/ongoing' },
    ],
  },
  {
    name: 'description',
    type: 'textarea',
    label: 'Treatment Description',
    placeholder: 'Detailed description of the treatment plan...',
    description: 'Comprehensive details about the treatment approach',
    gridColumn: 12,
    minRows: 3,
    maxRows: 5,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Progress notes, side effects, adjustments, outcomes...',
    description: 'Progress updates, observations, or important notes',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
