/**
 * Visit form field configuration
 */

import { tagsFieldConfig, getTodayEndOfDay } from './shared';

export const visitFormFields = [
  {
    name: 'reason',
    type: 'text',
    label: 'Reason for Visit',
    placeholder: 'e.g., Annual Checkup, Follow-up, Symptoms Review',
    required: true,
    description: 'Primary purpose of this medical visit',
    gridColumn: 12,
  },
  {
    name: 'date',
    type: 'date',
    label: 'Visit Date',
    placeholder: 'Select visit date',
    required: true,
    description: 'When the visit occurred',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'practitioner_id',
    type: 'select',
    label: 'Attending Practitioner',
    placeholder: 'Select practitioner (optional)',
    description: 'Doctor who conducted the visit',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'visit_type',
    type: 'select',
    label: 'Visit Type',
    placeholder: 'Select visit type',
    description: 'Type of medical visit',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      { value: 'annual checkup', label: 'Annual Checkup' },
      { value: 'follow-up', label: 'Follow-up' },
      { value: 'consultation', label: 'Consultation' },
      { value: 'emergency', label: 'Emergency' },
      { value: 'preventive care', label: 'Preventive Care' },
      { value: 'routine visit', label: 'Routine Visit' },
      { value: 'specialist referral', label: 'Specialist Referral' },
    ],
  },
  {
    name: 'priority',
    type: 'select',
    label: 'Priority',
    placeholder: 'Select priority level',
    description: 'Priority level of the visit',
    gridColumn: 6,
    clearable: true,
    options: [
      { value: 'routine', label: 'Routine' },
      { value: 'urgent', label: 'Urgent' },
      { value: 'emergency', label: 'Emergency' },
    ],
  },
  {
    name: 'condition_id',
    type: 'select',
    label: 'Related Condition (Optional)',
    placeholder: 'Select a condition this visit is related to',
    description: 'Link this visit to a specific condition if applicable',
    gridColumn: 12,
    searchable: true,
    clearable: true,
    dynamicOptions: 'conditions',
  },
  {
    name: 'chief_complaint',
    type: 'text',
    label: 'Chief Complaint',
    placeholder: 'Primary concern or symptom reported',
    description: 'Main health concern or symptom that prompted the visit',
    gridColumn: 12,
  },
  {
    name: 'duration_minutes',
    type: 'number',
    label: 'Duration (minutes)',
    placeholder: 'Visit duration',
    description: 'How long the visit lasted',
    gridColumn: 6,
    min: 1,
    max: 600,
  },
  {
    name: 'location',
    type: 'select',
    label: 'Location',
    labelKey: 'medical:visits.location.label',
    placeholderKey: 'medical:visits.location.placeholder',
    descriptionKey: 'medical:visits.location.description',
    placeholder: 'Where the visit occurred',
    description: 'Where the visit took place',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      { value: 'office', label: "Doctor's Office" },
      { value: 'hospital', label: 'Hospital' },
      { value: 'clinic', label: 'Clinic' },
      { value: 'telehealth', label: 'Telehealth/Virtual' },
      { value: 'urgent care', label: 'Urgent Care' },
      { value: 'emergency room', label: 'Emergency Room' },
      { value: 'home', label: 'Home Visit' },
    ],
  },
  {
    name: '_divider_clinical',
    type: 'divider',
    label: 'Clinical Information',
    gridColumn: 12,
  },
  {
    name: 'diagnosis',
    type: 'textarea',
    label: 'Diagnosis/Assessment',
    placeholder: 'Clinical assessment or diagnosis from the visit...',
    description: 'Medical diagnosis or clinical assessment',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
  },
  {
    name: 'treatment_plan',
    type: 'textarea',
    label: 'Treatment Plan',
    placeholder: 'Recommended treatment or next steps...',
    description: 'Treatment recommendations and prescribed interventions',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  {
    name: 'follow_up_instructions',
    type: 'textarea',
    label: 'Follow-up Instructions',
    placeholder: 'Follow-up care instructions...',
    description: 'Instructions for ongoing care and follow-up appointments',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
  },
  {
    name: 'notes',
    type: 'textarea',
    label: 'Additional Notes',
    labelKey: 'medical:visits.additionalNotes.label',
    placeholderKey: 'medical:visits.additionalNotes.placeholder',
    descriptionKey: 'medical:visits.additionalNotes.description',
    placeholder: 'Any other important details about the visit...',
    description: 'Any additional observations, notes, or important details',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
