"""Add name to procedures table

Revision ID: 7144f20f4b32
Revises: b0192437ef34
Create Date: 2025-06-11 22:03:57.859062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7144f20f4b32'
down_revision = 'b0192437ef34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('immunizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    # Removed op.drop_column('medications', 'effectivePeriod_start') - column doesn't exist in current DB
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # Skip adding 'name' column to procedures table - it already exists in database
    # op.add_column('procedures', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # Skip dropping 'name' column from procedures table - it should remain
    # op.drop_column('procedures', 'name')
    op.alter_column('patients', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Removed op.add_column('medications', sa.Column('effectivePeriod_start', sa.DATE(), nullable=True)) - not needed for current DB state
    op.alter_column('immunizations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
